[package]
name = "web_server_ver"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.31", features = ["serialize"] }
log = "0.4"
tokio = { version = "1.41.1", features = ["full"] }
dirs = "5.0"
futures = "0.3.31"
sea-orm = { version = "1.1.1", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
] }
sea-schema = "0.16.0"
sqlx = { version = "0.8.2", features = ["sqlite"] }
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
revitcli = "1.2.0"
rayon = "1.7"
db_manager = { path = "../db_manager" }
revit_check = { path = "../revit_check" }
print_err = { path = "../print_err" }
rocket = { version = "0.5.0-rc.3", features = ["json"] }
reqwest = { version = "0.11", features = ["json"] }
